### ISSUE TITLE
Check if it is possible to cache modules that were compiled at Runtime

### ISSUE THREAD

**Issue by sleipnir** [eigr/massa#42]
It may be possible to cache the modules that were created after the discovery and subsequent creation of the gRPC server. This would be useful for restarts of the container optimizing the boot time of the application, it could also be useful in case of initialization of replicas, if the cache is distributed.

Check if we can use: code.load_binary for this purpose, something like:

```
iex(massa@127.0.0.1)2> {_, mod, bytecode, _} = defmodule Foo do
...(massa@127.0.0.1)2>    def thing(), do: "hello"
...(massa@127.0.0.1)2> end
{:module, Foo,
 <<70, 79, 82, 49, 0, 0, 4, 208, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 123,
   0, 0, 0, 13, 10, 69, 108, 105, 120, 105, 114, 46, 70, 111, 111, 8, 95, 95,
   105, 110, 102, 111, 95, 95, 10, 97, 116, ...>>, {:thing, 0}}
iex(massa@127.0.0.1)3> 
iex(massa@127.0.0.1)4> :code.purge(Foo)
false

iex(massa@127.0.0.1)6> :code.delete(Foo)
true

iex(massa@127.0.0.1)8> :code.load_binary(mod, 'filename', bytecode)
{:module, Foo}

iex(massa@127.0.0.1)10> Foo.thing
"hello"
iex(massa@127.0.0.1)11>
```

**Comment by sleipnir** [comment]
I think that we could persist the generated bytecode in Mnesia, so that any other instance of the proxy of the same user function can have an improvement in its initialization because it doesn't need to compile the reflected modules.

**Comment by marcellanz** [comment]
the coce generation is done right after a discovery call, yes?

**Comment by sleipnir** [comment]
> the coce generation is done right after a discovery call, yes?

Yes!

**Comment by sleipnir** [comment]
I think it would be simple for the discovery callback signature to generate a hash that could be used as a cache, so if the hash stays the same it's safe to reuse the existing code, whereas if the hash has changed then it's because it deals with a new deploy, modified and therefore the compilation process on the fly must occur.
Obviously, this optimization can be turned on and off via configuration so that in case of problems the user can choose to pay the compilation cost

**Comment by sleipnir** [comment]
@wesleimp please comment your thoughts about it

**Comment by wesleimp** [comment]
> @wesleimp please comment your thoughts about it

Sorry @sleipnir, I didn't see this mention.

**Comment by wesleimp** [comment]
Closing due to [this commit](https://github.com/eigr/massa/commit/8f87cd8a3b2ebc4d70c0d99a3f57b563b881b51c)

**Comment by sleipnir** [comment]
> > @wesleimp please comment your thoughts about it
> 
> Sorry @sleipnir, I didn't see this mention.

No problem. Together we solve the problem for what it's worth
