### ISSUE TITLE
massa does not distinct between multiple gRPC services discovered.

### ISSUE THREAD

**Issue by marcellanz** [eigr/massa#52]
WIP

Log:
https://gist.github.com/marcellanz/fa8eee2c2a07332d45b00b6a2d72b559

**Comment by sleipnir** [comment]
It seems that there is a conceptual flaw in the protocol, as the proxy allows the registration of multiple entities but only one ServiceInfo is available. This confuses me a bit about how to handle it properly.

**Comment by sleipnir** [comment]
three services were generated in this forwarded log.
So I don't think I understand the problem.

```
services = [
    MassProxy.Reflection.Service,

    Cloudstate.Tck.Model.Action.ActionTwo.Service.ProxyService,

    Cloudstate.Tck.Model.Eventlogeventing.EventLogSubscriberModel.Service.ProxyService,

  ]
```

Two are from registered user roles and one is from the reflection grpc service.

**Comment by marcellanz** [comment]
great point and discovery.
its true and its like this (I don't say that is sane, btw)

discover() returns entityspecs, and one serviceinfo. the entityspecs have by themselves servicenames, that are the names of the gRPC services, the servicename from serviceinfo is "the servicename the proxy gets to know about", also the serviceinfo is described as:

```
// Information about the service that proxy is proxying to.
// All of the information in here is optional. It may be useful for debug purposes.
```

This was always a bit irritating. Having one "servicename" on toplevel with serviceinfo, but then servicenames on entities, where entities are really gRPC defined services. So in this regard, services where only versioned on the whole level, with the service info, not on gRPC service level. So a ServiceInfo "service" is the thing the proxy knows how to connect to, that is so far the "userfunction" or our cloudstate grpc server that we run in the pod which the proxy is its sidecar.

In that context, "userfunction" is similar confusing if I'm a developer coming out of a box. how can a whole collection of services, the gRPC services, be named userfunction. 

In AS it's still the same, altough they changed naming and Entities are now named Component:
https://github.com/eigr-labs/akkaserverless-protocol/blob/main/akkaserverless-proxy-protocol-0.7.0-beta.10/akkaserverless/protocol/discovery.proto

![D18BCFD6-AF24-4CCA-965D-801223289311](https://user-images.githubusercontent.com/12616445/123370477-17fe3d00-d580-11eb-8189-07a5d10b4f10.jpeg)

You know, there is only one real gRPC server running, and that is the Cloudstate Protocol Server, this server has a name, the servicename of the ServiceSpec. Then, there are "virtual" services that are defined as gRPC services and routed to registered entities, these have a "ServiceName" that are actually names of entities where we route to their methods to be called.

**Comment by marcellanz** [comment]
> three services were generated in this forwarded log.
> So I don't think I understand the problem.
> 
> ```
> services = [
>     MassProxy.Reflection.Service,
> 
>     Cloudstate.Tck.Model.Action.ActionTwo.Service.ProxyService,
> 
>     Cloudstate.Tck.Model.Eventlogeventing.EventLogSubscriberModel.Service.ProxyService,
> 
>   ]
> ```
> 
> Two are from registered user functions and one is from the reflection grpc service.

Problem is, the ActionTwo Service got methods generated that are from an another service:

![C9DD28AC-B4A1-4E35-9D6B-676D7820522C](https://user-images.githubusercontent.com/12616445/123373047-fe132900-d584-11eb-8779-686a7b43dbe3.jpeg)

I'm sorry for the sparingly started issue. I will provide an image to run against, with grpc calls to show the issue properly.

**Comment by sleipnir** [comment]
> @sleipnir great point and discovery.
> its true and its like this (I don't say that is sane, btw)
> ....

Yes there is only one Server serving many services

**Comment by sleipnir** [comment]
> Problem is, the ActionTwo Service got methods generated that are from an another service. ActionTwo servie has only one method, Call(). ProcessUnary() and ProcessStreamedIn() are from an another service:
> 

Now I get it.
I will review the proxy
