### ISSUE TITLE
New node joining does not receive entities from other nodes

### ISSUE THREAD

**Issue by drowzy** [eigr/massa#91]
**New node joining does not receive entities from other nodes**

A node joining a cluster does only dispatch a `{:join, entities}` to the other nodes of the cluster
but does not receive any information about the entities which the other nodes hold. So if a node joins after
another node the first node will not receive any entity information.

Edit: I noticed the orchestrator runs the discovery periodically, which will fix the issue I'm describing. It's however
once every minute, so perhaps another strategy can be considered as a new node joining the cluster possible won't have the correct topology for ~1 minute.

**To Reproduce**
1. Start two nodes, be sure to be running a user function on 8080:
```bash
# Will discover user function on 8080
NODE_COOKIE=secret PROXY_PORT=5000 PROXY_HTTP_PORT=5001 iex --name massa-001@127.0.0.1 -S mix

# Will have no entities
USER_FUNCTION_PORT=4000 NODE_COOKIE=secret iex --name massa-002@127.0.0.1 --cookie secret -S mix
```
2. Call `GenServer.call(MassaProxy.Entity.EntityRegistry, {:get, "cloudstate.action.ActionProtocol"})` to see that it's empty

**Expected behavior**
A node joining a cluster should receive information about the entities that is registered stred on that *node*.
I.e when a `EntityRegistry` receives a join message from it should respond to the node with the entities.

**Comment by sleipnir** [comment]
I'm not looking at the code right now but I believe only entities that don't belong to the same node would show up. Have you tried consulting on both nodes?

**Comment by drowzy** [comment]
It doesn't, it's dependent on the order in which they start. If you start node2 before node1. i.e node2 has no entities, node1 discovers user function on 8080, registers the entities and sends a `{:join, entities}` message. Then it will behave correctly but if you do it in the order I've described it won't correctly propagate.

The same if node1 has `entities=['a']` node2 joins with `entities=['b']`. Node1 will receive the join message and have `entities=['a', 'b']` but node2 will still have `entities=['b']. 

Proposed solution is to share entity information about on that node when receiving [:nodeup](https://github.com/eigr/massa/blob/master/apps/massa_proxy/lib/massa_proxy/cluster/entity/entity_registry.ex#L93)

**Comment by sleipnir** [comment]
What I've tried to say is that EntityRegistry won't keep a record of entity types that belong to itself, see if that line has nothing to do with what you're telling me

https://github.com/eigr/massa/blob/6822887f406b6f242358adf38cab0bfa9b613016/apps/massa_proxy/lib/massa_proxy/cluster/entity/entity_registry.ex#L83
